### ISSUE TITLE
This repo should not have the same approver group or approval process as other @opentdf implementation repos

### ISSUE THREAD

**Issue by bleggett** [opentdf/spec#5]
Q: Do we want a different set of approvers/CODEOWNERS for `opentdf/spec` versus the rest of opentdf - that is, the implementation?

**Comment by strantalis** [comment]
@pflynn-virtru @biscoe916 @cassandrabailey293 

Has anyone looked into this. Currently we have 56 developers as `CODEOWNERS` because the `developers` team is assigned to this repo. It looks the same on other repos. 

I feel like we should scope each repos `CODEOWNERS` to the core maintainers imo.
